# Omarchy environment (OMARCHY_PATH + PATH), needed even for non-interactive shells
[[ -r /usr/share/omarchy/default/bash/env-bootstrap ]] && source /usr/share/omarchy/default/bash/env-bootstrap

# If not running interactively, don't do anything else (leave this above the rc source)
[[ $- != *i* ]] && return

# ble.sh — command completion + syntax highlighting. Must be sourced before the
# rest of the rc and attached at the very end of this file.
if [[ -r ~/.local/share/blesh/ble.sh ]]; then
  source ~/.local/share/blesh/ble.sh --noattach --rcfile ~/.config/blesh/init.sh
fi

# Starship reads the prompt generated by omarchy-theme-set-templates from
# ~/.config/omarchy/themed/starship.toml.tpl, so the prompt re-colors itself on
# every `omarchy theme set`. Falls back to ~/.config/starship.toml if absent.
if [[ -r $HOME/.local/state/omarchy/current/theme/starship.toml ]]; then
  export STARSHIP_CONFIG="$HOME/.local/state/omarchy/current/theme/starship.toml"
fi

# All the default Omarchy aliases and functions
# (don't mess with these directly, just overwrite them here!)
source "$OMARCHY_PATH/default/bash/rc"

# Add your own exports, aliases, and functions here.
#
# Make an alias for invoking commands you use constantly
# alias p='python'

# Pick a random ASCII art from ~/.config/fastfetch/logos each run.
fastfetch() {
  local logos=(~/.config/fastfetch/logos/*.txt)
  if [[ -e ${logos[0]} ]]; then
    command fastfetch --logo-type file --logo "${logos[RANDOM % ${#logos[@]}]}" "$@"
  else
    command fastfetch "$@"
  fi
}

# Greet every new interactive shell.
fastfetch
[[ -r "$HOME/.cargo/env" ]] && . "$HOME/.cargo/env"

# Start ble.sh. Keep this last — it must see every binding set above.
[[ ${BLE_VERSION-} ]] && ble-attach

# Re-assert bindings that must beat the readline ones. Omarchy's inputrc maps
# TAB to readline's menu-complete, and ble.sh only translates those during
# ble-attach, so these have to come after it.
#
# TAB once  -> accept the ghost suggestion on the line (auto_complete keymap,
#              bound in ~/.config/blesh/init.sh)
# TAB twice -> open the candidate menu and pick from it
if [[ ${BLE_VERSION-} ]]; then
  ble-bind -m emacs -f TAB tab-accept-or-menu
  ble-bind -m emacs -f C-i tab-accept-or-menu   # same keystroke, other name
  if ble/is-function ble/widget/fzf-menu-complete; then
    ble-bind -m emacs -f 'M-/' fzf-menu-complete   # ALT-/ picks candidates in fzf
  fi
fi
