[DeviceInfo]
adaptiveNoiseLevel=50
conversationalAwareness=false
deviceName=👾 Mark III Pros 👾
hearingAidEnabled=false
magicAccEncKey=@ByteArray(I\xb5O\xb8\x63\x35.J\x98\xd7\xc7`e\np\f)
magicAccIRK=@ByteArray(u\"$\xb9\x65K\xa8+\x1b\x81\x92W\xbc$ \x19)
model=11
modelNumber=A3064
oneBudANCMode=true

[earDetection]
setting=2
