"$schema" = 'https://starship.rs/config-schema.json'

# GENERATED by omarchy-theme-set-templates from
#   ~/.config/omarchy/themed/starship.toml.tpl
# Edit the .tpl, then re-apply the theme. Editing this copy is pointless: it is
# rebuilt from the template every time `omarchy theme set` runs.
#
# Colors are theme placeholders, so the prompt re-skins itself with the desktop.
# Segment text sits on the theme background for the dark-on-pastel look.

add_newline = true
command_timeout = 500
palette = "omarchy"

format = """
[](fg:seg1)\
$os\
$username\
[](fg:seg1 bg:seg2)\
$directory\
[](fg:seg2 bg:seg3)\
$git_branch\
$git_status\
[](fg:seg3 bg:seg4)\
$nodejs\
$bun\
$deno\
$python\
$rust\
$golang\
$java\
$php\
$c\
$lua\
$ruby\
$docker_context\
[](fg:seg4 bg:seg5)\
$time\
[](fg:seg5)[](fg:trail2)[](fg:trail3)\
$cmd_duration\
$character"""

[palettes.omarchy]
# Two-accent gradient. Instead of grabbing five fixed ANSI slots (which made a
# rainbow that ignored the theme), the bar interpolates between two of the
# theme's OWN colours: its signature `accent` through to `bright_magenta`.
# Verified across all 11 installed themes -- both keys always resolve to hex,
# and dark `ink` text clears WCAG AA on every stop (worst case 4.82:1).
seg1 = "{{ accent }}"
seg2 = "{{ mix accent bright_magenta 25% }}"
seg3 = "{{ mix accent bright_magenta 50% }}"
seg4 = "{{ mix accent bright_magenta 75% }}"
seg5 = "{{ bright_magenta }}"
# Comet trail: the closing arrow, then two more dissolving into the background.
trail2 = "{{ mix bright_magenta background 52% }}"
trail3 = "{{ mix bright_magenta background 76% }}"
ink = "{{ background }}"
# Kept outside the gradient on purpose, so a failed command still reads as red.
alert = "{{ red }}"
muted = "{{ muted }}"

[os]
disabled = false
format = "[ $symbol ]($style)"
style = "fg:ink bg:seg1"

[os.symbols]
# Omarchy sets ID=omarchy in /etc/os-release, so starship reports Linux, not Arch.
Linux = ""
Arch = ""
Unknown = ""

[username]
show_always = true
format = "[$user ]($style)"
style_user = "fg:ink bg:seg1"
style_root = "fg:ink bg:seg1"

[directory]
format = "[ $path ]($style)"
style = "fg:ink bg:seg2"
truncation_length = 3
truncation_symbol = "…/"
truncate_to_repo = true
read_only = " "
read_only_style = "fg:ink bg:seg2"

[git_branch]
symbol = ""
format = "[ $symbol $branch ]($style)"
style = "fg:ink bg:seg3"

[git_status]
format = "[$all_status$ahead_behind]($style)"
style = "fg:ink bg:seg3"
ahead = "⇡${count} "
diverged = "⇕⇡${ahead_count}⇣${behind_count} "
behind = "⇣${count} "
conflicted = "! "
up_to_date = ""
untracked = "? "
modified = "* "
stashed = "$ "
staged = "+ "
renamed = "» "
deleted = "✘ "

[nodejs]
symbol = ""
format = "[ $symbol $version ]($style)"
style = "fg:ink bg:seg4"

[bun]
symbol = ""
format = "[ $symbol $version ]($style)"
style = "fg:ink bg:seg4"

[deno]
symbol = ""
format = "[ $symbol $version ]($style)"
style = "fg:ink bg:seg4"

[python]
symbol = ""
format = "[ $symbol $version ]($style)"
style = "fg:ink bg:seg4"

[rust]
symbol = ""
format = "[ $symbol $version ]($style)"
style = "fg:ink bg:seg4"

[golang]
symbol = ""
format = "[ $symbol $version ]($style)"
style = "fg:ink bg:seg4"

[java]
symbol = ""
format = "[ $symbol $version ]($style)"
style = "fg:ink bg:seg4"

[php]
symbol = ""
format = "[ $symbol $version ]($style)"
style = "fg:ink bg:seg4"

[c]
symbol = ""
format = "[ $symbol $version ]($style)"
style = "fg:ink bg:seg4"

[lua]
symbol = ""
format = "[ $symbol $version ]($style)"
style = "fg:ink bg:seg4"

[ruby]
symbol = ""
format = "[ $symbol $version ]($style)"
style = "fg:ink bg:seg4"

[docker_context]
symbol = ""
format = "[ $symbol $context ]($style)"
style = "fg:ink bg:seg4"

[time]
disabled = false
time_format = "%R"
format = "[  $time ]($style)"
style = "fg:ink bg:seg5"

[cmd_duration]
min_time = 2000
format = " [ $duration]($style)"
style = "fg:muted"

[character]
success_symbol = " [❯](bold fg:seg1)"
error_symbol = " [❯](bold fg:alert)"
vimcmd_symbol = " [❮](bold fg:seg5)"
