-- Generated by omaoptions — do not edit by hand.
-- Vertical scroll speed per Logitech mouse (Hyprland per-device scroll_factor).
-- Change it in the OmaOptions bar panel, then Apply.

hl.device({ name = "logitech-usb-receiver-mouse", scroll_factor = 1 })
hl.device({ name = "mx-master-3s", scroll_factor = 1 })
